import Flutter
import UIKit
import FaceTecSDK

// ─── FaceTec MethodChannel ─────────────────────────────────────────────────
// Exposed methods:
//   "startLiveness"  → { faceScanBase64, auditTrailImage, sessionId, livenessMatchScore? }
//                      accepts optional arg: { "enrollmentRefId": String }
//   "startIDMatch"   → { faceScanBase64, auditTrailImage, sessionId,
//                        idFrontPhoto, idBackPhoto,
//                        fullName, curp, dateOfBirth, matchLevel, enrollmentRefId }
// ─────────────────────────────────────────────────────────────────────────────

class FaceTecChannel: NSObject {

    // Developer keys auto-generated by FaceTec Configuration Wizard
    private static let deviceKeyIdentifier = "dtRMttUJar6pYp2CTF4M5sCcvpzBsyfj"
    private static let faceScanEncryptionKey =
        "-----BEGIN PUBLIC KEY-----\n" +
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5PxZ3DLj+zP6T6HFgzzk\n" +
        "M77LdzP3fojBoLasw7EfzvLMnJNUlyRb5m8e5QyyJxI+wRjsALHvFgLzGwxM8ehz\n" +
        "DqqBZed+f4w33GgQXFZOS4AOvyPbALgCYoLehigLAbbCNTkeY5RDcmmSI/sbp+s6\n" +
        "mAiAKKvCdIqe17bltZ/rfEoL3gPKEfLXeN549LTj3XBp0hvG4loQ6eC1E1tRzSkf\n" +
        "GJD4GIVvR+j12gXAaftj3ahfYxioBH7F7HQxzmWkwDyn3bqU54eaiB7f0ftsPpWM\n" +
        "ceUaqkL2DZUvgN0efEJjnWy5y1/Gkq5GGWCROI9XG/SwXJ30BbVUehTbVcD70+ZF\n" +
        "8QIDAQAB\n" +
        "-----END PUBLIC KEY-----"
    private static let faceTecBaseURL = "https://api.facetec.com/api/v3.1/biometrics"

    private static var sdkReady = false

    static func register(with messenger: FlutterBinaryMessenger) {
        let channel = FlutterMethodChannel(name: "verifia/facetec", binaryMessenger: messenger)
        let instance = FaceTecChannel()
        channel.setMethodCallHandler(instance.handle)

        // Initialize SDK at registration time so it's ready when needed
        initializeSDK()
    }

    private static func initializeSDK() {
        guard !sdkReady else { return }
        FaceTec.sdk.initializeInDevelopmentMode(
            deviceKeyIdentifier: deviceKeyIdentifier,
            faceScanEncryptionKey: faceScanEncryptionKey
        ) { [self] success in
            sdkReady = success
            if success {
                print("[FaceTec] SDK initialized successfully")
                FaceTec.sdk.setCustomization(FaceTecChannel.buildCustomization())
            } else {
                print("[FaceTec] SDK initialization failed: \(FaceTec.sdk.description(for: FaceTec.sdk.getStatus()))")
            }
        }
    }

    private func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "startLiveness":
            let args = call.arguments as? [String: Any]
            let enrollmentRefId = args?["enrollmentRefId"] as? String
            startLivenessSession(enrollmentRefId: enrollmentRefId, result: result)
        case "startIDMatch":
            let args = call.arguments as? [String: Any]
            let idType = args?["idType"] as? String ?? "INE"
            startIDMatchSession(idType: idType, result: result)
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // ─── Start a full 3D liveness session ────────────────────────────────────

    private func startLivenessSession(enrollmentRefId: String?, result: @escaping FlutterResult) {
        guard FaceTecChannel.sdkReady else {
            FaceTecChannel.initializeSDK()
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                self.startLivenessSession(enrollmentRefId: enrollmentRefId, result: result)
            }
            return
        }

        fetchSessionToken { sessionToken in
            guard let token = sessionToken else {
                result(FlutterError(code: "SESSION_TOKEN_ERROR",
                                   message: "No se pudo obtener token de sesión FaceTec",
                                   details: nil))
                return
            }
            DispatchQueue.main.async {
                self.launchFaceTecSession(sessionToken: token, enrollmentRefId: enrollmentRefId, result: result)
            }
        }
    }

    private func launchFaceTecSession(sessionToken: String, enrollmentRefId: String?, result: @escaping FlutterResult) {
        guard let rootVC = UIApplication.shared.connectedScenes
            .compactMap({ $0 as? UIWindowScene })
            .flatMap({ $0.windows })
            .first(where: { $0.isKeyWindow })?.rootViewController else {
            result(FlutterError(code: "NO_VC", message: "No hay ViewController raíz", details: nil))
            return
        }

        let processor = FaceTecLivenessProcessor(
            sessionToken: sessionToken,
            enrollmentRefId: enrollmentRefId,
            presentingVC: rootVC,
            result: result
        )
        objc_setAssociatedObject(rootVC, &FaceTecChannel.processorKey, processor, .OBJC_ASSOCIATION_RETAIN)
    }

    private static var processorKey  = "facetecProcessor"
    private static var idProcessorKey = "facetecIDProcessor"

    // ─── Start a Photo ID Match session ──────────────────────────────────────

    private func startIDMatchSession(idType: String, result: @escaping FlutterResult) {
        guard FaceTecChannel.sdkReady else {
            FaceTecChannel.initializeSDK()
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                self.startIDMatchSession(idType: idType, result: result)
            }
            return
        }

        fetchSessionToken { sessionToken in
            guard let token = sessionToken else {
                result(FlutterError(code: "SESSION_TOKEN_ERROR",
                                   message: "No se pudo obtener token de sesión FaceTec",
                                   details: nil))
                return
            }
            DispatchQueue.main.async {
                self.launchFaceTecIDMatch(sessionToken: token, idType: idType, result: result)
            }
        }
    }

    private func launchFaceTecIDMatch(sessionToken: String, idType: String, result: @escaping FlutterResult) {
        guard let rootVC = UIApplication.shared.connectedScenes
            .compactMap({ $0 as? UIWindowScene })
            .flatMap({ $0.windows })
            .first(where: { $0.isKeyWindow })?.rootViewController else {
            result(FlutterError(code: "NO_VC", message: "No hay ViewController raíz", details: nil))
            return
        }

        let processor = FaceTecIDMatchProcessor(
            sessionToken: sessionToken,
            idType: idType,
            presentingVC: rootVC,
            result: result
        )
        objc_setAssociatedObject(rootVC, &FaceTecChannel.idProcessorKey, processor, .OBJC_ASSOCIATION_RETAIN)
    }

    // ─── Fetch session token from FaceTec dev server ─────────────────────────

    private func fetchSessionToken(completion: @escaping (String?) -> Void) {
        let url = URL(string: FaceTecChannel.faceTecBaseURL + "/session-token")!
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue(FaceTecChannel.deviceKeyIdentifier, forHTTPHeaderField: "X-Device-Key")
        let userAgent = FaceTec.sdk.createFaceTecAPIUserAgentString("")
        request.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        request.setValue(userAgent, forHTTPHeaderField: "X-User-Agent")

        URLSession.shared.dataTask(with: request) { data, _, error in
            guard let data = data,
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                  let token = json["sessionToken"] as? String else {
                print("[FaceTec] Failed to get session token: \(error?.localizedDescription ?? "unknown")")
                completion(nil)
                return
            }
            completion(token)
        }.resume()
    }

    // ─── UI Customization matching VerifiA purple theme ──────────────────────

    private static func buildCustomization() -> FaceTecCustomization {
        let purple = UIColor(red: 0.42, green: 0.39, blue: 1.0, alpha: 1.0)
        let white  = UIColor.white
        let custom = FaceTecCustomization()

        custom.frameCustomization.backgroundColor = white
        custom.frameCustomization.borderColor = purple
        custom.frameCustomization.cornerRadius = 16

        custom.overlayCustomization.backgroundColor = UIColor(red: 0.07, green: 0.07, blue: 0.07, alpha: 1.0)

        custom.ovalCustomization.strokeColor = purple
        custom.ovalCustomization.progressColor1 = purple
        custom.ovalCustomization.progressColor2 = purple

        let gradient = CAGradientLayer()
        gradient.colors = [purple.cgColor, purple.cgColor]
        gradient.locations = [0, 1]
        gradient.startPoint = CGPoint(x: 0, y: 0)
        gradient.endPoint   = CGPoint(x: 1, y: 0)
        custom.feedbackCustomization.backgroundColor = gradient
        custom.feedbackCustomization.textColor = white

        custom.guidanceCustomization.foregroundColor = purple
        custom.guidanceCustomization.buttonBackgroundNormalColor    = purple
        custom.guidanceCustomization.buttonBackgroundHighlightColor = UIColor(red: 0.33, green: 0.30, blue: 0.80, alpha: 1.0)
        custom.guidanceCustomization.buttonTextNormalColor          = white

        custom.resultScreenCustomization.foregroundColor = purple
        custom.resultScreenCustomization.activityIndicatorColor      = purple
        custom.resultScreenCustomization.resultAnimationBackgroundColor = purple
        custom.resultScreenCustomization.resultAnimationForegroundColor = white
        custom.resultScreenCustomization.uploadProgressFillColor     = purple

        custom.securityWatermarkImage = .faceTec
        custom.cancelButtonCustomization.location = .topLeft

        return custom
    }
}

// ─── Liveness Processor ───────────────────────────────────────────────────────
// Handles the FaceTec session lifecycle:
//   1. User completes session → processSessionWhileFaceTecSDKWaits fires
//   2. We POST faceScan to FaceTec dev server → get scanResultBlob
//   3. Pass blob back → SDK shows success animation → onFaceTecSDKCompletelyDone
//   4. Return faceScanBase64 to Flutter via result callback

class FaceTecLivenessProcessor: NSObject, FaceTecFaceScanProcessorDelegate {

    private let flutterResult: FlutterResult
    /// The enrollmentRefId stored at registration time (for 3D-3D match)
    private let registrationEnrollmentRefId: String?

    private var faceScanCallback: FaceTecFaceScanResultCallback?
    private var faceScanBase64: String?
    private var auditTrailImage: String?
    private var sessionId: String?
    private var livenessMatchScore: Int?
    private var success = false

    /// Temporary enrollment ID for this liveness session (used as "live side" in 3D-3D match)
    private let tempEnrollmentId: String

    private let deviceKey = "dtRMttUJar6pYp2CTF4M5sCcvpzBsyfj"
    private let baseURL   = "https://api.facetec.com/api/v3.1/biometrics"

    init(sessionToken: String, enrollmentRefId: String?, presentingVC: UIViewController, result: @escaping FlutterResult) {
        self.flutterResult = result
        self.registrationEnrollmentRefId = enrollmentRefId
        self.tempEnrollmentId = "verifia-verify-\(UUID().uuidString)"
        super.init()
        let vc = FaceTec.sdk.createSessionVC(faceScanProcessorDelegate: self, sessionToken: sessionToken)
        presentingVC.present(vc, animated: true)
    }

    func processSessionWhileFaceTecSDKWaits(sessionResult: FaceTecSessionResult,
                                             faceScanResultCallback: FaceTecFaceScanResultCallback) {
        self.faceScanCallback = faceScanResultCallback
        self.sessionId = sessionResult.sessionId

        guard sessionResult.status == .sessionCompletedSuccessfully,
              let faceScan = sessionResult.faceScanBase64 else {
            faceScanResultCallback.onFaceScanResultCancel()
            return
        }

        self.faceScanBase64 = faceScan
        self.auditTrailImage = sessionResult.auditTrailCompressedBase64?.first

        // Step 1: POST /enrollment-3d to enroll the live face temporarily
        var params: [String: Any] = [
            "faceScan": faceScan,
            "externalDatabaseRefID": tempEnrollmentId
        ]
        if let audit = sessionResult.auditTrailCompressedBase64?.first       { params["auditTrailImage"] = audit }
        if let low   = sessionResult.lowQualityAuditTrailCompressedBase64?.first { params["lowQualityAuditTrailImage"] = low }

        post(path: "/enrollment-3d", params: params, sessionId: sessionResult.sessionId) { [weak self] json in
            guard let self = self else { return }

            let blob = json?["scanResultBlob"] as? String ?? "dev-bypass"
            let enrollOk = !blob.isEmpty

            // Step 2: If we have a registration enrollment, do 3D-3D match
            if enrollOk, let regId = self.registrationEnrollmentRefId {
                let matchParams: [String: Any] = [
                    "enrollmentIdentifier":       self.tempEnrollmentId,
                    "sourceEnrollmentIdentifier": regId
                ]
                self.post(path: "/match-3d-3d", params: matchParams, sessionId: sessionResult.sessionId) { [weak self] matchJson in
                    guard let self = self else { return }
                    if let level = matchJson?["matchLevel"] as? Int {
                        self.livenessMatchScore = level * 10
                        print("[FaceTec] 3D-3D match score: \(level) → \(level * 10)/100")
                    } else {
                        print("[FaceTec] match-3d-3d response: \(matchJson ?? [:])")
                    }
                    self.success = faceScanResultCallback.onFaceScanGoToNextStep(scanResultBlob: blob)
                }
            } else {
                // No registration enrollment provided — skip match step
                self.success = faceScanResultCallback.onFaceScanGoToNextStep(scanResultBlob: blob)
            }
        }
    }

    func onFaceTecSDKCompletelyDone() {
        if success, let faceScan = faceScanBase64 {
            var resultDict: [String: Any] = [
                "faceScanBase64": faceScan,
                "auditTrailImage": auditTrailImage ?? "",
                "sessionId": sessionId ?? ""
            ]
            if let score = livenessMatchScore {
                resultDict["livenessMatchScore"] = score
            }
            flutterResult(resultDict)
        } else {
            flutterResult(FlutterError(code: "LIVENESS_CANCELLED",
                                       message: "Verificación de presencia cancelada",
                                       details: nil))
        }
    }

    private func post(path: String, params: [String: Any], sessionId: String,
                      completion: @escaping ([String: Any]?) -> Void) {
        var request = URLRequest(url: URL(string: baseURL + path)!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(deviceKey, forHTTPHeaderField: "X-Device-Key")
        let ua = FaceTec.sdk.createFaceTecAPIUserAgentString(sessionId)
        request.setValue(ua, forHTTPHeaderField: "User-Agent")
        request.setValue(ua, forHTTPHeaderField: "X-User-Agent")
        request.httpBody = try? JSONSerialization.data(withJSONObject: params)

        URLSession.shared.dataTask(with: request) { data, _, _ in
            guard let data = data,
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                completion(nil)
                return
            }
            completion(json)
        }.resume()
    }
}

// ─── Photo ID Match Processor ─────────────────────────────────────────────────
// Flow:
//   1. 3D Liveness face scan → POST /enrollment-3d → get scanResultBlob
//   2. ID scan (INE/passport) → POST /match-3d-2d-idscan → get matchLevel + OCR data
//   3. Return all data to Flutter via FlutterResult

class FaceTecIDMatchProcessor: NSObject, FaceTecFaceScanProcessorDelegate, FaceTecIDScanProcessorDelegate {

    private let flutterResult: FlutterResult
    private let idType: String

    private var faceScanCallback: FaceTecFaceScanResultCallback?
    private var idScanCallback: FaceTecIDScanResultCallback?
    private var faceScanBase64: String?
    private var auditTrailImage: String?
    private var sessionId: String?
    private var idFrontPhoto: String?
    private var idBackPhoto: String?
    private var fullName: String?
    private var curp: String?
    private var dateOfBirth: String?
    private var matchLevel: Int = 0
    private var enrollmentId: String
    private var success = false

    private let deviceKey = "dtRMttUJar6pYp2CTF4M5sCcvpzBsyfj"
    private let baseURL   = "https://api.facetec.com/api/v3.1/biometrics"

    init(sessionToken: String, idType: String, presentingVC: UIViewController, result: @escaping FlutterResult) {
        self.flutterResult = result
        self.idType = idType
        self.enrollmentId = "verifia-\(UUID().uuidString)"
        super.init()

        // Configure Spanish upload messages
        FaceTecCustomization.setIDScanUploadMessageOverrides(
            frontSideUploadStarted: "Subiendo\nFrente del ID",
            frontSideStillUploading: "Subiendo...\nConexión lenta",
            frontSideUploadCompleteAwaitingResponse: "Carga completa",
            frontSideUploadCompleteAwaitingProcessing: "Procesando\nID",
            backSideUploadStarted: "Subiendo\nReverso del ID",
            backSideStillUploading: "Subiendo...\nConexión lenta",
            backSideUploadCompleteAwaitingResponse: "Carga completa",
            backSideUploadCompleteAwaitingProcessing: "Procesando\nReverso",
            userConfirmedInfoUploadStarted: "Guardando\nTus Datos",
            userConfirmedInfoStillUploading: "Subiendo...\nConexión lenta",
            userConfirmedInfoUploadCompleteAwaitingResponse: "Datos Guardados",
            userConfirmedInfoUploadCompleteAwaitingProcessing: "Procesando",
            nfcUploadStarted: "Subiendo\nDetalles NFC",
            nfcStillUploading: "Subiendo...\nConexión lenta",
            nfcUploadCompleteAwaitingResponse: "Carga completa",
            nfcUploadCompleteAwaitingProcessing: "Procesando\nNFC",
            skippedNFCUploadStarted: "Subiendo\nDetalles del ID",
            skippedNFCStillUploading: "Subiendo...\nConexión lenta",
            skippedNFCUploadCompleteAwaitingResponse: "Carga completa",
            skippedNFCUploadCompleteAwaitingProcessing: "Procesando\nDetalles"
        )

        let vc = FaceTec.sdk.createSessionVC(
            faceScanProcessorDelegate: self,
            idScanProcessorDelegate: self,
            sessionToken: sessionToken
        )
        presentingVC.present(vc, animated: true)
    }

    // ─── Step 1: Face scan → enrollment-3d ───────────────────────────────────

    func processSessionWhileFaceTecSDKWaits(sessionResult: FaceTecSessionResult,
                                             faceScanResultCallback: FaceTecFaceScanResultCallback) {
        self.faceScanCallback = faceScanResultCallback
        self.sessionId = sessionResult.sessionId

        guard sessionResult.status == .sessionCompletedSuccessfully,
              let faceScan = sessionResult.faceScanBase64 else {
            faceScanResultCallback.onFaceScanResultCancel()
            return
        }

        self.faceScanBase64 = faceScan
        self.auditTrailImage = sessionResult.auditTrailCompressedBase64?.first

        var params: [String: Any] = [
            "faceScan": faceScan,
            "externalDatabaseRefID": enrollmentId
        ]
        if let audit = sessionResult.auditTrailCompressedBase64?.first { params["auditTrailImage"] = audit }
        if let low  = sessionResult.lowQualityAuditTrailCompressedBase64?.first { params["lowQualityAuditTrailImage"] = low }

        post(path: "/enrollment-3d", params: params, sessionId: sessionResult.sessionId) { [weak self] json in
            guard let self = self else { return }
            if let blob = json?["scanResultBlob"] as? String {
                _ = faceScanResultCallback.onFaceScanGoToNextStep(scanResultBlob: blob)
            } else {
                // Dev fallback
                print("[FaceTec ID] enrollment-3d failed — continuing anyway")
                _ = faceScanResultCallback.onFaceScanGoToNextStep(scanResultBlob: "dev-bypass")
            }
        }
    }

    // ─── Step 2: ID scan → match-3d-2d-idscan ────────────────────────────────

    func processIDScanWhileFaceTecSDKWaits(idScanResult: FaceTecIDScanResult,
                                            idScanResultCallback: FaceTecIDScanResultCallback) {
        self.idScanCallback = idScanResultCallback

        guard idScanResult.status == .success else {
            idScanResultCallback.onIDScanResultCancel()
            return
        }

        self.idFrontPhoto = idScanResult.frontImagesCompressedBase64?.first
        self.idBackPhoto  = idScanResult.backImagesCompressedBase64?.first

        var params: [String: Any] = [
            "idScan": idScanResult.idScanBase64 ?? "",
            "minMatchLevel": 3,
            "externalDatabaseRefID": enrollmentId
        ]
        if let front = idScanResult.frontImagesCompressedBase64?.first { params["idScanFrontImage"] = front }
        if let back  = idScanResult.backImagesCompressedBase64?.first  { params["idScanBackImage"]  = back  }

        post(path: "/match-3d-2d-idscan", params: params, sessionId: idScanResult.sessionId ?? "") { [weak self] json in
            guard let self = self else { return }

            if let json = json, let blob = json["scanResultBlob"] as? String {
                // Log full response for debugging
                print("[FaceTec ID] match-3d-2d-idscan response keys: \(json.keys.sorted())")
                if let jsonData = try? JSONSerialization.data(withJSONObject: json, options: .prettyPrinted),
                   let jsonStr = String(data: jsonData, encoding: .utf8) {
                    print("[FaceTec ID] Full response:\n\(jsonStr)")
                }

                // Match level (FaceTec returns 0–10; multiply by 10 for 0–100 display)
                if let level = json["matchLevel"] as? Int { self.matchLevel = level * 10 }

                // Extract OCR data — try multiple possible response structures.
                // FaceTec INE returns: givenName, surname, secondSurname (or firstName/lastName/fullName).
                // Strip standalone "-" tokens that FaceTec inserts for empty middle-name fields.
                func clean(_ s: String) -> String {
                    s.components(separatedBy: .whitespaces)
                     .filter { $0 != "-" && !$0.isEmpty }
                     .joined(separator: " ")
                }

                func extractName(_ d: [String: Any]) -> String? {
                    // Prefer explicit full name
                    if let n = d["fullName"] as? String, !clean(n).isEmpty { return clean(n) }

                    // Mexican INE field names used by FaceTec OCR
                    let given  = d["givenName"]     as? String ?? d["firstName"]  as? String ?? ""
                    let pat    = d["surname"]        as? String ?? d["lastName"]   as? String ?? ""
                    let mat    = d["secondSurname"]  as? String ?? ""

                    // Build "APELLIDO_PAT APELLIDO_MAT NOMBRE(S)" — standard Mexican order
                    let parts  = [pat, mat, given].map { clean($0) }.filter { !$0.isEmpty }
                    let combined = parts.joined(separator: " ")
                    return combined.isEmpty ? nil : combined
                }

                // Priority: userConfirmedDetails (user-edited on Review & Confirm screen) > data > top-level
                if let confirmed = json["userConfirmedDetails"] as? [String: Any] {
                    if let name = extractName(confirmed), self.fullName == nil { self.fullName = name }
                    self.dateOfBirth = self.dateOfBirth ?? confirmed["dob"] as? String ?? confirmed["dateOfBirth"] as? String
                    self.curp        = self.curp        ?? confirmed["curp"] as? String ?? confirmed["CURP"] as? String
                }
                if let data = json["data"] as? [String: Any] {
                    if let name = extractName(data), self.fullName == nil { self.fullName = name }
                    self.dateOfBirth = self.dateOfBirth ?? data["dob"] as? String ?? data["dateOfBirth"] as? String
                    if let extra = data["additionalSessionData"] as? [String: Any] {
                        self.curp = self.curp ?? extra["curp"] as? String ?? extra["CURP"] as? String
                        if let name = extractName(extra), self.fullName == nil { self.fullName = name }
                    }
                }
                if let name = extractName(json), self.fullName == nil { self.fullName = name }
                if let extra = json["additionalSessionData"] as? [String: Any] {
                    if let name = extractName(extra), self.fullName == nil { self.fullName = name }
                    self.curp = self.curp ?? extra["curp"] as? String ?? extra["CURP"] as? String
                }
                if self.dateOfBirth == nil {
                    self.dateOfBirth = json["dob"] as? String ?? json["dateOfBirth"] as? String
                }

                print("[FaceTec ID] Parsed — name: \(self.fullName ?? "nil"), curp: \(self.curp ?? "nil"), dob: \(self.dateOfBirth ?? "nil"), matchLevel: \(self.matchLevel)")
                self.success = idScanResultCallback.onIDScanResultProceedToNextStep(scanResultBlob: blob)
            } else {
                // Dev fallback: proceed without server validation
                print("[FaceTec ID] match-3d-2d-idscan failed — using dev bypass")
                self.success = true
                idScanResultCallback.onIDScanResultCancel()
            }
        }
    }

    func onFaceTecSDKCompletelyDone() {
        if success || (idFrontPhoto != nil) {
            var result: [String: Any] = [
                "faceScanBase64": faceScanBase64 ?? "",
                "auditTrailImage": auditTrailImage ?? "",
                "sessionId": sessionId ?? "",
                "idFrontPhoto": idFrontPhoto ?? "",
                "idBackPhoto": idBackPhoto ?? "",
                "matchLevel": matchLevel,
                "enrollmentRefId": enrollmentId,
            ]
            if let name = fullName    { result["fullName"]    = name }
            if let c    = curp        { result["curp"]        = c    }
            if let dob  = dateOfBirth { result["dateOfBirth"] = dob  }
            flutterResult(result)
        } else {
            flutterResult(FlutterError(code: "ID_MATCH_CANCELLED",
                                       message: "Escaneo de ID cancelado",
                                       details: nil))
        }
    }

    // ─── Helper: POST to FaceTec dev server ──────────────────────────────────

    private func post(path: String, params: [String: Any], sessionId: String,
                      completion: @escaping ([String: Any]?) -> Void) {
        var request = URLRequest(url: URL(string: baseURL + path)!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(deviceKey, forHTTPHeaderField: "X-Device-Key")
        let ua = FaceTec.sdk.createFaceTecAPIUserAgentString(sessionId)
        request.setValue(ua, forHTTPHeaderField: "User-Agent")
        request.setValue(ua, forHTTPHeaderField: "X-User-Agent")
        request.httpBody = try? JSONSerialization.data(withJSONObject: params)

        URLSession.shared.dataTask(with: request) { data, _, _ in
            guard let data = data,
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                completion(nil)
                return
            }
            completion(json)
        }.resume()
    }
}
